name: Deploying
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    name: Deploying dev version to Testflight
    runs-on: macOS-latest
    environment: development
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install gpg
        run: brew install gpg
      - name: Change Provisiong Profiles permissions
        run: chmod +x ./.github/secrets/decrypt_secrets.sh
      - name: gpg version fix
        run: export PATH="/opt/homebrew/opt/openssl@1.1/bin:$PATH"
      - name: Setup provisioning profile
        env:
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
        run: ./.github/secrets/decrypt_secrets.sh
      - name: Archiving project
        env:
          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: ./.github/scripts/archive_dev_app.sh
      - name: Exporting .ipa
        run: ./.github/scripts/export_ipa.sh
      - name: Publishing app
        if: success()
        env:
          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
        run: ./.github/scripts/publish_testflight.sh